{% set name = "cytominer_database" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e16bfe3f635e65d8725232f213a046fedda46f78b5b330fb2e33563eebff685

build:
  number: 0
  noarch: python
  entry_points:
    - cytominer-database=cytominer_database.command:command
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.4
    - backports.tempfile >=1.0rc1
    - click >=6.7
    - configparser >=3.5.0
    - csvkit >=1.0.2
    - pandas >=0.20.3
    - pip
    - python
    - setuptools
  run:
    - python >=3.4
    - backports.tempfile >=1.0rc1
    - click >=6.7
    - configparser >=3.5.0
    - csvkit >=1.0.2
    - pandas >=0.20.3
    - python
    - setuptools

test:
  imports:
    - cytominer_database
    - cytominer_database.commands
  commands:
    - cytominer-database --help

about:
  home: https://github.com/cytomining/cytominer-database
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: cytominer-database provides command-line tools for organizing measurements extracted from images.
  description: Software tools such as CellProfiler can extract hundreds of measurements from millions of cells in a typical high-throughput imaging experiment. The measurements are stored across thousands of CSV files. cytominer-database helps you organize these data into a single database backend, such as SQLite.
  doc_url: https://readthedocs.org/projects/cytominer-database/
  dev_url: https://github.com/cytomining/cytominer-database

extra:
  recipe-maintainers:
    - gwaybio
