{% set name = "cytominer_database" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9dfd1e5c49d085656ce32e716a6d8e95b2b3418433e75aefae4662f1ca7da6ec

build:
  number: 1
  noarch: python
  entry_points:
    - cytominer-database=cytominer_database.command:command
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - click >=6.7
    - configparser >=3.5.0
    - csvkit >=1.0.2
    - pandas >=0.20.3
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=6.7
    - configparser >=3.5.0
    - csvkit >=1.0.2
    - pandas >=0.20.3
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - cytominer_database
    - cytominer_database.commands
  commands:
    - cytominer-database --help

about:
  home: https://github.com/cytomining/cytominer-database
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: cytominer-database provides command-line tools for organizing measurements extracted from images.
  description: Software tools such as CellProfiler can extract hundreds of measurements from millions of cells in a typical high-throughput imaging experiment. The measurements are stored across thousands of CSV files. cytominer-database helps you organize these data into a single database backend, such as SQLite.
  doc_url: https://readthedocs.org/projects/cytominer-database/
  dev_url: https://github.com/cytomining/cytominer-database

extra:
  recipe-maintainers:
    - gwaybio
    - d33bs
